from selenium.webdriver.common.by import By


class AmazonSearchLocators:

    ADD_TO_CART_BUTTON_LOCATOR = ('ID', 'TODO_ADD_TO_CART_BUTTON_LOCATOR')
    FIRST_PRODUCT_LOCATOR = ('ID', 'TODO_FIRST_PRODUCT_LOCATOR')
    SEARCH_BOX_LOCATOR = ('ID', 'TODO_SEARCH_BOX_LOCATOR')
    SEARCH_BUTTON_LOCATOR = ('ID', 'TODO_SEARCH_BUTTON_LOCATOR')
