"""
tests/api/test_api_demo.py

API automation tests using pytest + requests + pytest-asyncio + Allure.
Auto-generated by the RAG pipeline from structured test cases.

Interview talking point:
  "For API tests, the auto-gen pipeline produces tests in this format.
  Each test validates status code, response schema, and business logic.
  Allure captures request/response details for each step."
"""
import allure
import pytest
import requests
import httpx


BASE_URL = "https://jsonplaceholder.typicode.com"


# ── Synchronous API tests ────────────────────────────────────────────────────

@allure.suite("API Smoke Suite")
@allure.feature("Posts API")
@allure.story("GET all posts returns 200")
@allure.severity(allure.severity_level.CRITICAL)
def test_get_posts_returns_200():
    with allure.step("Send GET /posts"):
        response = requests.get(f"{BASE_URL}/posts")

    with allure.step("Assert status 200"):
        allure.attach(str(response.status_code), name="status_code",
                      attachment_type=allure.attachment_type.TEXT)
        assert response.status_code == 200

    with allure.step("Assert response is a list"):
        data = response.json()
        assert isinstance(data, list)
        assert len(data) > 0


@allure.suite("API Smoke Suite")
@allure.feature("Posts API")
@allure.story("GET single post returns correct schema")
@allure.severity(allure.severity_level.CRITICAL)
def test_get_single_post_schema():
    with allure.step("Send GET /posts/1"):
        response = requests.get(f"{BASE_URL}/posts/1")

    with allure.step("Assert status 200"):
        assert response.status_code == 200

    with allure.step("Validate response schema"):
        data = response.json()
        allure.attach(str(data), name="response_body",
                      attachment_type=allure.attachment_type.JSON)
        assert "id" in data
        assert "title" in data
        assert "body" in data
        assert "userId" in data
        assert data["id"] == 1


@allure.suite("API Regression Suite")
@allure.feature("Posts API")
@allure.story("POST creates new resource")
@allure.severity(allure.severity_level.NORMAL)
def test_create_post():
    payload = {"title": "AI Generated Test", "body": "auto-gen content", "userId": 1}

    with allure.step("Send POST /posts"):
        allure.attach(str(payload), name="request_body",
                      attachment_type=allure.attachment_type.JSON)
        response = requests.post(f"{BASE_URL}/posts", json=payload)

    with allure.step("Assert 201 Created"):
        assert response.status_code == 201

    with allure.step("Assert created resource has an id"):
        data = response.json()
        assert "id" in data


# ── Async API tests (pytest-asyncio) ────────────────────────────────────────

@allure.suite("API Regression Suite")
@allure.feature("Posts API")
@allure.story("Async GET post returns correct data")
@allure.severity(allure.severity_level.NORMAL)
async def test_async_get_post():
    """
    Async test using httpx — same pattern as calling an async LLM agent endpoint.
    Interview talking point: 'I use async tests when the system under test
    is an async FastAPI endpoint or an async LangGraph agent.'
    """
    async with httpx.AsyncClient() as client:
        with allure.step("Async GET /posts/1"):
            response = await client.get(f"{BASE_URL}/posts/1")

    with allure.step("Assert status 200 and body"):
        assert response.status_code == 200
        data = response.json()
        allure.attach(str(data), name="async_response",
                      attachment_type=allure.attachment_type.JSON)
        assert data["id"] == 1


@allure.suite("API Regression Suite")
@allure.feature("Posts API")
@allure.story("Async parallel API calls complete successfully")
@allure.severity(allure.severity_level.NORMAL)
async def test_async_parallel_calls():
    """
    Simulates async parallel calls — useful for load testing agent endpoints.
    """
    import asyncio

    async with httpx.AsyncClient() as client:
        with allure.step("Fire 3 parallel requests"):
            responses = await asyncio.gather(
                client.get(f"{BASE_URL}/posts/1"),
                client.get(f"{BASE_URL}/posts/2"),
                client.get(f"{BASE_URL}/posts/3"),
            )

    with allure.step("Assert all returned 200"):
        for resp in responses:
            assert resp.status_code == 200
